In [1]:
import numpy as np
import pandas as pd

In [2]:
sample_array = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
sample_array[0:8]

array([10, 11, 12, 13, 14, 15, 16, 17])

In [4]:
sample_array[1,5,8]

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [5]:
sample_array[[0,4,7]]

array([10, 14, 17])

In [44]:
sample=np.array([[[100,2,3],[2,4,6],[20,30,40]]])

In [35]:
type(sample)

numpy.ndarray

In [39]:
sample

array([[[ 1,  2,  3],
        [ 2,  4,  6],
        [20, 30, 40]]])

In [41]:
sample[0,1,2]

6

In [45]:
sample[:,0,0]

array([100])

In [2]:
list_=[1,2,3,5]
sum=0
for val in list_:
    sum+=val
print(sum)

11


In [5]:
a=0;
b=0
while (a<10):
    b=b+a
    a=a+1
else:
    print("The sum of first 9 intergers: ",b)

The sum of first 9 intergers:  45


In [6]:
A = 'ABCDEFG'

for i in [0, 1, 2, 3, 4, 5, 6]:
    print(str(i)*2)

00
11
22
33
44
55
66


In [11]:
def ABC(a):
    a= 'ABCDE'
    for i in a:
        print('It is ',str(i))

b='01234'
ABC(b)

It is  A
It is  B
It is  C
It is  D
It is  E


In [12]:
func=(lambda x,y:(x**y))
func(func(2,2))

TypeError: <lambda>() missing 1 required positional argument: 'y'

In [13]:
def func(x):
    return lambda y: (x + y + 1)

def func1(x):
    return lambda y : (func(x)(x)+y+1)

print(func1(3)(1))

9


In [14]:
A= list(range(5))
B = map(lambda x: (x * x)+1, A)
print(list(B))

[1, 2, 5, 10, 17]


In [15]:
for i in range(4):
    print(i)

0
1
2
3
